server.port=8080
spring.application.name=devpulse

spring.datasource.url=jdbc:postgresql://localhost:5432/devpulse
spring.datasource.username=devpulse_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent

management.endpoints.web.exposure.inlcude=health,info
management.endpoint.health.show-details=always
